image: python:3.7

stages:
  - build
  - deploy

PDF build:
  image: tianon/latex
  stage: build
  script:
    - apt-get update -y
    - apt-get install -y locales
    - cd docs
    - echo "sk_SK ISO-8859-2\nsk_SK.UTF-8 UTF-8" >> /etc/locale.gen
    - locale-gen
    - export TIMEZONE="Europe/Bratislava"
    - export KEYMAP="sk-qwerty.map.gz"
    - export LANG="sk_SK"
    - export LC_ALL=sk_SK.UTF-8
    - export LANGUAGE="sk_SK:sk"
    - latexmk -bibtex -pdf -outdir=out/ paperwork.tex
  artifacts:
    paths:
      - docs/out/paperwork.pdf

PDF deploy:
  stage: deploy
  cache:
    paths:
      - gdrive
  before_script:
    - mkdir ~/.aws/
    - touch ~/.aws/credentials
    - pip install awscli
    - printf "[eb-cli]\naws_access_key_id = %s\naws_secret_access_key = %s\n" "$AWS_ACCESS_KEY_ID" "$AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials
    - if [ ! -f "./gdrive" ]; then wget -O gdrive https://github.com/gdrive-org/gdrive/releases/download/2.1.0/gdrive-linux-x64 ; fi
    - chmod +x ./gdrive
    - mkdir -p ~/.gdrive && echo $GOOGLE_APP_AUTH > ~/.gdrive/token.json
  script:
    - aws s3 sync ./docs/out s3://storage-zuffik/ --acl public-read --exclude "*" --include "paperwork.pdf"
    - ./gdrive -c ~/.gdrive --service-account token.json list
    - ./gdrive -c ~/.gdrive --service-account token.json update $GOOGLE_DRIVE_FILE_ID docs/out/paperwork.pdf
